#Ficheiro para ambiente de desenvolvimento
#Railway nao suporta ficheiros docker-compose.yml

version: '3.8'

services:
  backend:
    env_file:
      - .env
    build: 
      context: .
    network_mode: "host"
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    #ports:
    #  - 8000:8000
    