# Generated by Django 4.0.4 on 2023-10-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('duration', models.SmallIntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership.membershiptype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('admission_fees', models.DecimalField(decimal_places=2, max_digits=20)),
                ('training_start', models.TimeField()),
                ('training_end', models.TimeField()),
                ('status', models.CharField(max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership.member')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership.membership')),
                ('training_objective', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership.trainingobjective')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ManyToManyField(through='membership.MemberMembership', to='membership.membership'),
        ),
    ]
