# Generated by Django 4.0.4 on 2023-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermembership',
            name='training_objective',
        ),
        migrations.AddField(
            model_name='member',
            name='training_objectives',
            field=models.ManyToManyField(to='membership.trainingobjective'),
        ),
    ]
