# Generated by Django 4.0.4 on 2023-11-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_remove_membermembership_training_objective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('entrance_timestamp', models.DateTimeField()),
                ('exit_timestamp', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
