# Generated by Django 5.0.3 on 2024-04-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='user',
            new_name='member',
        ),
    ]
