# Generated by Django 4.0.4 on 2023-11-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='exit_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
