# Generated by Django 4.0.4 on 2023-11-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_attendance_exit_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='entrance_timestamp',
            new_name='entrance_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='exit_timestamp',
            new_name='exit_time',
        ),
    ]
