# Generated by Django 5.0.3 on 2024-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_preferences_member_alter_preferences_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='messageType',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
