# Generated by Django 5.0.3 on 2024-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_preferences_messagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='messageType',
            field=models.CharField(max_length=100),
        ),
    ]
