# Generated by Django 4.0.4 on 2023-11-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_attendance_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entrance_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='exit_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membermembership',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingobjective',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
