# Generated by Django 4.0.4 on 2025-05-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_membermembership_auto_renwe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermembership',
            old_name='auto_renwe',
            new_name='auto_renew',
        ),
    ]
