# Generated by Django 4.0.4 on 2023-08-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_remove_members_gym_owner_remove_members_membership_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberMemberships',
            new_name='MemberMembership',
        ),
    ]
