# Generated by Django 4.0.4 on 2023-10-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_rename_membermemberships_membermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermembership',
            name='admission_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermembership',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermembership',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermembership',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membermembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership.members'),
        ),
        migrations.AlterField(
            model_name='membermembership',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('member_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membermembership')),
            ],
        ),
    ]
