# Generated by Django 4.0.4 on 2023-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_membermembership_admission_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='membership',
            field=models.ManyToManyField(through='membership.MemberMembership', to='membership.membership'),
        ),
    ]
