# Generated by Django 4.0.4 on 2023-10-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_members_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_duration',
            field=models.SmallIntegerField(),
        ),
    ]
